import { Router } from 'express';
import authRoutes from './auth';
import financeRoutes from './finance';
import productsRoutes from './products';
import invoicesRoutes from './invoices';
import reportsRoutes from './reports';
import customersRoutes from './customers';
import warehousesRoutes from './warehouses';
import suppliersRoutes from './suppliers';
import purchaseOrdersRoutes from './purchaseOrders';
import employeesRoutes from './employees';
import projectsRoutes from './projects';
import accountsRoutes from './accounts';
const router = Router();
router.use('/auth', authRoutes);
router.use('/finance', financeRoutes);
router.use('/products', productsRoutes);
router.use('/invoices', invoicesRoutes);
router.use('/reports', reportsRoutes);
router.use('/customers', customersRoutes);
router.use('/warehouses', warehousesRoutes);
router.use('/suppliers', suppliersRoutes);
router.use('/purchase-orders', purchaseOrdersRoutes);
router.use('/employees', employeesRoutes);
router.use('/projects', projectsRoutes);
router.use('/accounts', accountsRoutes);
export default router;
